// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1608048264);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1608048384);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1608048023);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1608048143);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1608048506);
user_pref("browser.cache.disk.amount_written", 484);
user_pref("browser.cache.disk.capacity", 798720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "RU");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 09 Dec 2020 20:38:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1608048265);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200629235513");
user_pref("extensions.lastAppVersion", "68.10.0");
user_pref("extensions.lastPlatformVersion", "68.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"4d9d4f8f-fe9c-4fd3-981a-60fb766ce441\",\"default-theme@mozilla.org\":\"989c27b8-3984-47d0-94ae-8f9689c36f5c\",\"yandex@search.mozilla.org\":\"1bf1672d-7ae0-4852-93b0-c3158df36234\",\"google@search.mozilla.org\":\"59535df0-9211-45c1-86c0-a6abb1f63ad8\",\"ddg@search.mozilla.org\":\"52aab04d-5c46-48de-9878-3ad9de6c457b\",\"ozonru@search.mozilla.org\":\"d98b9b0a-5e52-4750-8e53-9f6a6787af90\",\"priceru@search.mozilla.org\":\"95799e9c-fed3-4f6f-ad7b-37920d0ed84d\",\"wikipedia@search.mozilla.org\":\"a06a5050-f70e-49c9-8816-20f4ed37f6d1\",\"mailru@search.mozilla.org\":\"209548f4-3e80-4d40-96f3-914692dcf288\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1608048723);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "6ed1f34e-9238-4358-97b3-807ba4120dd");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.10.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1608048724);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "3402ca19-a993-4bef-ad6f-02bcd3fec406");
user_pref("services.blocklist.pinning.checked", 1608048144);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1608040702226\"");
user_pref("services.settings.last_update_seconds", 1608048144);
user_pref("services.settings.main.hijack-blocklists.last_check", 1608048144);
user_pref("services.settings.main.language-dictionaries.last_check", 1608048144);
user_pref("services.settings.main.sites-classification.last_check", 1608048144);
user_pref("services.settings.security.onecrl.checked", 1608048144);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1608048723);
user_pref("toolkit.telemetry.cachedClientID", "a0f806cd-0e94-4cf4-a3e8-adc36b322e3d");
user_pref("toolkit.telemetry.prompted", 2);
